name: openstack
base: core22
summary: Dead simple OpenStack installation
license: Apache-2.0
description: |
  snap-openstack aims to provide a scalable, simple to deploy OpenStack solution.
version: yoga

confinement: strict
grade: devel

architectures:
  - build-on: amd64


system-usernames:
  snap_daemon: shared

layout:
  /usr/share/terraform/plugins:
    symlink: $SNAP_DATA/terraform-plugins

apps:
  clusterd:
    command: commands/clusterd.start
    restart-condition: on-failure
    daemon: simple
    plugs:
      - network
      - network-bind
  sunbeam:
    command: bin/sunbeam
    plugs:
      - dot-local-share-juju
      - dot-kube
      - home
      - network
      - network-bind
      - ssh-keys
    environment:
      PATH: $PATH:$SNAP/juju/bin
  terraform:
    command: bin/terraform
    plugs:
      - home
      - network
      - ssh-public-keys
      - juju-client-observe
    environment:
      PATH: $PATH:$SNAP/juju/bin

parts:
  sunbeam:
    plugin: python
    source: .
    build-packages:
      - git
    python-requirements:
      - requirements.txt
    override-build: |
      craftctl default
      snap-helpers write-hooks

  dqlite:
    build-attributes: [core22-step-dependencies]
    after:
      - raft
    source: https://github.com/canonical/dqlite
    source-type: git
    source-depth: 1
    plugin: autotools
    autotools-configure-parameters:
      - --prefix=
    stage-packages:
      - libuv1
      - libsqlite3-0
    build-packages:
      - libuv1-dev
      - libsqlite3-dev
      - pkg-config
    organize:
      usr/lib/: lib/
    prime:
      - lib/libdqlite*so*
      - lib/*/libuv*

  raft:
    build-attributes: [core22-step-dependencies]
    source: https://github.com/canonical/raft
    source-type: git
    source-depth: 1
    plugin: autotools
    autotools-configure-parameters:
      - --prefix=
    stage-packages:
      - libuv1
      - liblz4-1
    build-packages:
      - libuv1-dev
      - liblz4-dev
      - pkg-config
    organize:
      usr/lib/: lib/
    prime:
      - lib/libraft*so*
      - lib/*/libuv.so*

  sunbeam-cluster:
    after:
      - dqlite
    plugin: go
    source: https://github.com/openstack-snaps/sunbeam-microcluster
    source-depth: 1
    source-type: git
    build-snaps:
      - go
    build-environment:
      - GOFLAGS: "-mod=readonly"
    override-build: |
      set -ex

      # Setup build environment
      export CGO_CFLAGS="-I${SNAPCRAFT_STAGE}/include/ -I${SNAPCRAFT_STAGE}/usr/local/include/"
      export CGO_LDFLAGS="-L${SNAPCRAFT_STAGE}/lib/ -L${SNAPCRAFT_STAGE}/usr/local/lib/"
      export CGO_LDFLAGS_ALLOW="(-Wl,-wrap,pthread_create)|(-Wl,-z,now)"

      # Build the binaries
      go build -o "${SNAPCRAFT_PART_INSTALL}/bin/sunbeamd" -tags=libsqlite3 ./cmd/sunbeamd
    prime:
      - bin/sunbeamd

  terraform:
    plugin: go
    source: https://github.com/hashicorp/terraform
    source-depth: 1
    source-type: git
    source-tag: "v1.3.7"
    build-snaps: [go]
    build-environment:
      - CGO_ENABLED: "0"
      - GOFLAGS: "-mod=readonly"
    override-build: |
      go mod download
      go build -ldflags "-s -w"
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      cp terraform $SNAPCRAFT_PART_INSTALL/bin/terraform
    stage:
      - bin/terraform

  terraform-plan:
    after: [terraform]
    plugin: dump
    source: cloud/
    override-build: |
      craftctl default
      cd $SNAPCRAFT_PART_INSTALL/etc/deploy-microk8s
      $SNAPCRAFT_STAGE/bin/terraform providers mirror $SNAPCRAFT_STAGE/terraform-providers

  wrappers:
    plugin: dump
    source: snap-wrappers/

plugs:
  juju-bin:
    interface: content
    content: juju
    target: $SNAP/juju

  dot-local-share-juju:
    interface: personal-files
    write:
      - $HOME/.local/share/juju

  dot-kube:
    interface: personal-files
    read:
      - $HOME/.kube
