name: TICS scan

on:
  schedule:
    - cron: '30 3 * * 1'
  workflow_dispatch:

permissions:
  contents: read

jobs:
    TICS:
      runs-on: [self-hosted, linux, amd64, tiobe]
      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Setup GO
          uses: actions/setup-go@v4
          with:
            go-version: '1.22'

        - name: Install dependencies
          run: |
            sudo add-apt-repository -y ppa:dqlite/dev
            sudo apt install build-essential dqlite-tools libdqlite-dev libraft-canonical-dev -y

            python -m pip install tox

            go install honnef.co/go/tools/cmd/staticcheck@v0.5.1

        - name: Run sunbeam-python coverage tests
          working-directory: ./sunbeam-python
          run: tox -e cover

        - name: Build and run microcluster tests
          working-directory: ./sunbeam-microcluster
          run: |
            make build

        - name: Install snap dependencies
          run: |
            pip3 install --upgrade pip
            for f in $(find -name '*requirements.txt'); do
              echo "${f}"
              pip3 install --requirement "${f}"
            done

        - name: TICS
          uses: tiobe/tics-github-action@v3
          with:
            mode: qserver
            viewerUrl: https://canonical.tiobe.com/tiobeweb/TICS/api/cfg?name=default
            ticsAuthToken: ${{ secrets.TICSAUTHTOKEN }}
            project: snap-openstack
            branchdir: ${{ env.GITHUB_WORKSPACE }}
            installTics: true
