name: TICS scan

on:
  schedule:
    - cron: '30 3 * * 1'
  workflow_dispatch:

permissions:
  contents: read

jobs:
    TICS:
      runs-on: [self-hosted, linux, amd64, tiobe, noble]
      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Setup GO
          uses: actions/setup-go@v4
          with:
            go-version: '1.24'

        - name: Install dependencies
          run: |
            sudo add-apt-repository -y ppa:dqlite/dev
            sudo apt install build-essential libdqlite1.17-dev tox -y

            sudo snap install astral-uv --channel latest/stable --classic

            go install honnef.co/go/tools/cmd/staticcheck@v0.6.1

        - name: Run sunbeam-python coverage tests
          working-directory: ./sunbeam-python
          run: tox -e cover -- tests/unit

        - name: Build and run microcluster tests
          working-directory: ./sunbeam-microcluster
          run: |
            make build

        - name: Install snap dependencies
          working-directory: ./sunbeam-python
          run: |
            uv sync --all-extras
            source .venv/bin/activate

        - name: TICS
          uses: tiobe/tics-github-action@v3
          with:
            mode: qserver
            viewerUrl: https://canonical.tiobe.com/tiobeweb/TICS/api/cfg?name=GoProjects
            ticsAuthToken: ${{ secrets.TICSAUTHTOKEN }}
            project: snap-openstack
            branchdir: ${{ env.GITHUB_WORKSPACE }}
            installTics: true
